---
- hosts: all
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: 
        name: nginx 
        state: latest
    
    - name: start nginx
      command: service nginx start

    - name: install mysql
      apt:
        name: mysql-server
        state: latest

    - name: start mysql
      command: service mysql start

    - name: "Create log tree"
      file:
        path: "/tmp/logs"
        state: directory
        owner: root
        group: root
